config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sessions#new'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/:id' => 'contacts#index'
  resources :users

  resources :contacts


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  validates_format_of :email, :with => /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i, :message => 'Invalid Email'
  before_save :capitalize_first_and_last

  def capitalize_first_and_last
    self.first_name.capitalize!
    self.last_name.capitalize!

  end





end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :password, presence: true, confirmation: true
  validates :password_confirmation, presence: true
  has_secure_password
  has_many :contacts, dependent: :destroy

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      random_password = SecureRandom.urlsafe_base64
      user.provider = auth.provider
      user.email = auth.info.email
      user.password = random_password
      user.password_confirmation = random_password
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end







end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :require_login

  def current_user
    if session[:user_id] && User.exists?(session[:user_id])
      User.find(session[:user_id])
    end
  end

  def require_login
    unless current_user
      flash[:alert] = "Please login first"
      redirect_to root_path
    end
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :require_login
  def index
    @user = current_user
    @contacts = Contact.all
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    user = current_user
    @contact.user_id = user.id
    if @contact.save
      redirect_to "/#{user.id}"
    end
  end

  def show
    @user = current_user
    #shows contacts if and only if they exist and match the user id
    @contact = Contact.find(params[:id]) if Contact.exists?(params[:id])
    if @contact && @user.id == @contact.user_id
      render "show.html.erb"
    else
      redirect_to root_path
    end
  end

  def destroy
    contact = Contact.find(params[:id])
    contact.destroy
    redirect_to '/'
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    contact = Contact.find(params[:id])
    if contact.update(contact_params)
      redirect_to contacts_path
    else
      flash[:alert] = 'Email invalid'
      redirect_to edit_contact_path(contact.id)
    end
  end

private

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :note, :email, :phone)
  end

end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :check_signed_in, only: :new


  def check_signed_in
    if current_user
      redirect_to "/#{current_user.id}"
    end
  end


  def new
  end

  def create
    user = User.find_by_email(params[:email])

      if env["omniauth.auth"]
        user = User.from_omniauth(env["omniauth.auth"])
        session[:user_id]=user.id
        redirect_to "/#{user.id}"

      elsif user && user.authenticate(params[:password])
        session[:user_id] = user.id
        # flash[:alert] = "Success!"
        redirect_to "/#{user.id}"

      else
        flash[:alert] = "Invalid authentication"
        redirect_to '/login'
      end
  end

    def destroy
      if current_user
        session[:user_id] = nil
        redirect_to '/login'
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: :destroy
  before_action :check_signed_in, only: :new

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      current_user = @user
      session[:user_id] = current_user.id
      redirect_to "/#{current_user.id}"
    else
      flash[:alert] = 'Your information was missing or invalid. Please try again.'
      redirect_to '/signup'
    end
  end

  def destroy
      current_user.destroy
      session[:user_id] = nil
      flash[:alert] = 'Account deleted!'
      redirect_to '/'

  end

  def check_signed_in
    if current_user
      redirect_to "/#{current_user.id}"
    end
  end


  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/_contact_form.html.erb
<%= form_for @contact do |f| %>
<%= f.label :first_name %>
<%= f.text_field :first_name%><br />
<%= f.label :last_name %>
<%= f.text_field :last_name %><br />
<%= f.label :email %>
<%= f.text_field :email%><br />
<%= f.label :phone %>
<%= f.text_field :phone%><br />
<%= f.label :note%>
<%= f.text_area :note%>
<%= f.submit "SAVE" %>

  <% end %>

app/views/contacts/edit.html.erb
<h1>Editing <%= @contact.first_name %> <%= @contact.last_name %></h1>



<%= render 'contact_form' %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>



<% @contacts.each do |contact| %>
  <% if contact.user_id == @user.id %>

    <div>
      <a href="<%=contact_path(contact)%>"><h2><%= contact.first_name + " " + contact.last_name %></h2></a>
      <p><%= contact.email %> ||  <%= contact.phone %></p>
      <p>---------------------------------------------</p>
      <p>NOTES: <%= contact.note  %></p>

      <p>---------------------------------------------</p>

      <p> <%= link_to 'EDIT CONTACT', edit_contact_path(contact.id) %>  ||  <%= link_to "DELETE CONTACT", contact_path(contact.id), :method => :delete%>

    </div>


  <% end %>
<% end %>

app/views/contacts/new.html.erb
<h1>Create a new contact</h1>

<%= render 'contact_form' %>

app/views/contacts/show.html.erb
    <div>
      <h2>Showing <%= @contact.first_name + " " + @contact.last_name %></h2>
      <p><%= @contact.email %> ||  <%= @contact.phone %></p>
      <p>NOTES: <%= @contact.note  %></p>

      <p>---------------------------------------------</p>

      <p><%= link_to 'EDIT CONTACT', edit_contact_path(@user.id, @contact.id) %>  ||  <%= link_to "DELETE CONTACT", contact_path(@user.id, @contact.id), :method => :delete%>

    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KineticCrm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag :defaults %>
    <link href="https://fonts.googleapis.com/css?family=Audiowide|Exo+2" rel="stylesheet">
  </head>

  <body>
    <header>
      <h1 class="title">Rolodex</h1>
      <h4 class="subtitle">contact information database</h4>
      <% if current_user %>
        <p class = 'login_status'>Signed in as <%= current_user.email %> | <a href="/logout">Logout</a> | <%= link_to "DELETE ACCOUNT", user_path(current_user.id), :method => :delete, data: {confirm: "This action will PERMANANTLY delete your account and all of your contacts. Continue?"}%>
      </p>


      <ul class="nav">
        <a href="/<%= current_user.id %>"><li class="navlink">List all contacts</li></a>
        <a href="/contacts/new"><li class="navlink">Add a contact</li></a>
        <a href="/"><li class="navlink">About</li></a>

      </ul>
<% end %>
<h4 id="alert"><%= flash[:alert] %></h4>




    </header>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1 id="main_title">Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :password%>
<%= f.password_field :password %>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<%= f.submit "Submit" %>

<% end %>
<%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>